// generated by Fast Light User Interface Designer (fluid) version 1.0304
#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *janela_principal;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *start;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *fmg;
extern Fl_Value_Input *populacao;
extern Fl_Value_Input *mutacao_inicial;
#include <FL/Fl_Shared_Image.H>
#include <FL/Fl_PNG_Image.H>
extern Fl_PNG_Image *png;
#include <FL/Fl_Box.H>
extern Fl_Box *background;
#include <FL/fl_draw.H>
#include <FL/Fl_Chart.H>
extern Fl_Chart *fitness;
extern Fl_Chart *distancia_thebestofthebest;
#include <FL/fl_ask.H>
#endif
